apiVersion: v1
kind: Service
metadata:
  name: gitops-app
  namespace: dev
spec:
  selector:
    app: gitops-app
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
