image:
  repository: 700800570325.dkr.ecr.ap-south-1.amazonaws.com/dev-gitops-app
  tag: cf3acebdf725d0c806ff5d2a02cde8c3cf913887
  pullPolicy: Always
replicaCount: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 80
